InfoBox:
    Enabled: Yes
    CheckEcon: Yes
    CheckerTicksInterval: 2
    # Applies to Heal and Food only when <= DangerValue
    DangerValue: 6
    DiffLastSeconds: 10

System:
    # Change this to get you and this plugin eaten by Ender Dragon, not really, seriously.
    PluginVersion: ${version}